/**
 * @krexa/x402-middleware
 *
 * One-line Express middleware that gates routes behind x402 Payment Required.
 * AI agents holding a Krexa wallet automatically satisfy the challenge by
 * attaching an `X-Payment-Token` header generated by `krexa.agent.payX402()`.
 *
 * Merchant usage:
 * ```ts
 * import { krexaPaywall } from '@krexa/x402-middleware';
 *
 * app.use('/api/premium', krexaPaywall({
 *   recipient: process.env.MERCHANT_WALLET!,
 *   amountUsdc: 0.01,          // $0.01 per request
 *   krexa: { baseUrl: 'https://api.krexa.xyz', apiKey: process.env.KREXA_API_KEY },
 * }));
 * ```
 *
 * Agent usage (client side):
 * ```ts
 * const token = await krexa.agent.payX402({ recipient, amount: 0.01 });
 * fetch('/api/premium/data', { headers: { 'X-Payment-Token': token.paymentToken } });
 * ```
 */

import type { Request, Response, NextFunction, RequestHandler } from 'express';
import type { Chain } from '@krexa/sdk';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface KrexaPaywallOptions {
  /**
   * Merchant's USDC wallet address (Solana pubkey or EVM address).
   * Payments from agents will be sent here.
   */
  recipient: string;

  /**
   * Price per request in USDC. e.g. 0.01 for one cent.
   */
  amountUsdc: number;

  /**
   * Krexa backend connection config.
   */
  krexa?: {
    baseUrl?: string;
    apiKey?: string;
    chain?: Chain;
  };

  /**
   * Optional: verify the payment token against the Krexa oracle before
   * allowing the request through (requires API key with oracle access).
   * Default: false (trust-but-verify via header presence only in dev mode).
   */
  verify?: boolean;

  /**
   * Optional: called when a payment is successfully verified.
   * Useful for logging / rate-limiting per agent.
   */
  onPayment?: (info: PaymentInfo, req: Request) => void | Promise<void>;

  /**
   * Optional: custom 402 response body.
   */
  paymentRequired?: (req: Request) => X402Challenge;
}

export interface PaymentInfo {
  /** Decoded agent address from payment token. */
  agentAddress: string;
  /** Amount paid in USDC. */
  amountUsdc: number;
  /** Payment ID from the token. */
  paymentId: string;
  /** Unix timestamp (seconds). */
  paidAt: number;
}

export interface X402Challenge {
  /** Must be "x402" for protocol compliance. */
  scheme: 'x402';
  /** Payment details the agent needs to fulfill. */
  paymentRequired: {
    recipient: string;
    amountUsdc: number;
    chain: string;
    currency: 'USDC';
    /** Opaque challenge nonce; agents embed this in the payment token. */
    nonce: string;
    /** Unix timestamp; agents must pay before this. */
    expiresAt: number;
  };
  /** URL of the Krexa docs for agent-side integration. */
  docsUrl: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function generateNonce(): string {
  // Simple nonce: timestamp + 6 random hex chars
  return `${Date.now().toString(36)}-${Math.random().toString(16).slice(2, 8)}`;
}

/**
 * Decode a JWT-like base64url payment token without verifying the signature
 * (verification is done server-side via the Krexa oracle when `verify: true`).
 */
function decodePaymentToken(token: string): PaymentInfo | null {
  try {
    const parts = token.split('.');
    if (parts.length < 2) return null;
    const payload = Buffer.from(parts[1]!, 'base64url').toString('utf-8');
    const data = JSON.parse(payload) as {
      sub?: string;
      amt?: number;
      jti?: string;
      iat?: number;
    };
    return {
      agentAddress: data.sub ?? '',
      amountUsdc:   data.amt ?? 0,
      paymentId:    data.jti ?? '',
      paidAt:       data.iat ?? 0,
    };
  } catch {
    return null;
  }
}

/**
 * Call the Krexa oracle to verify a payment token is valid and settled.
 * Returns true if the oracle confirms the payment.
 */
async function verifyWithOracle(
  token: string,
  recipient: string,
  amountUsdc: number,
  krexa: NonNullable<KrexaPaywallOptions['krexa']>,
): Promise<boolean> {
  const baseUrl = (krexa.baseUrl ?? 'https://api.krexa.xyz').replace(/\/$/, '');
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (krexa.apiKey) headers['X-API-Key'] = krexa.apiKey;

  try {
    const res = await fetch(`${baseUrl}/api/v1/oracle/verify-payment`, {
      method: 'POST',
      headers,
      body: JSON.stringify({ token, recipient, amountUsdc }),
    });
    if (!res.ok) return false;
    const body = await res.json() as { valid?: boolean };
    return body.valid === true;
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Middleware factory
// ---------------------------------------------------------------------------

/**
 * Express middleware that requires an x402 payment token on every request.
 *
 * Responds with HTTP 402 + a JSON challenge if no valid token is present.
 * Pass-through if `X-Payment-Token` header is present and (optionally) verified.
 */
export function krexaPaywall(options: KrexaPaywallOptions): RequestHandler {
  const {
    recipient,
    amountUsdc,
    krexa = {},
    verify = false,
    onPayment,
    paymentRequired: customChallenge,
  } = options;

  const chain = krexa.chain ?? 'solana';

  return async function x402PaywallMiddleware(
    req: Request,
    res: Response,
    next: NextFunction,
  ): Promise<void> {
    const token = req.headers['x-payment-token'] as string | undefined;

    if (!token) {
      const nonce = generateNonce();
      const challenge: X402Challenge = customChallenge
        ? customChallenge(req)
        : {
            scheme: 'x402',
            paymentRequired: {
              recipient,
              amountUsdc,
              chain,
              currency: 'USDC',
              nonce,
              expiresAt: Math.floor(Date.now() / 1000) + 300, // 5 min window
            },
            docsUrl: 'https://docs.krexa.xyz/x402',
          };

      res.status(402).json(challenge);
      return;
    }

    // Optionally verify with oracle
    if (verify) {
      const valid = await verifyWithOracle(token, recipient, amountUsdc, krexa);
      if (!valid) {
        res.status(402).json({ error: 'Payment token invalid or not settled' });
        return;
      }
    }

    // Decode and surface payment info to downstream handlers
    const info = decodePaymentToken(token);
    if (info && onPayment) {
      try {
        await onPayment(info, req);
      } catch {
        // Non-fatal — don't block the request for a callback error
      }
    }

    // Attach payment info for downstream route handlers
    if (info) {
      (req as Request & { payment?: PaymentInfo }).payment = info;
    }

    next();
  };
}

// ---------------------------------------------------------------------------
// Utility: build an x402 challenge manually (for custom 402 flows)
// ---------------------------------------------------------------------------

export function buildX402Challenge(
  recipient: string,
  amountUsdc: number,
  chain: Chain = 'solana',
): X402Challenge {
  return {
    scheme: 'x402',
    paymentRequired: {
      recipient,
      amountUsdc,
      chain,
      currency: 'USDC',
      nonce: generateNonce(),
      expiresAt: Math.floor(Date.now() / 1000) + 300,
    },
    docsUrl: 'https://docs.krexa.xyz/x402',
  };
}

// ---------------------------------------------------------------------------
// Re-export types for consumers
// ---------------------------------------------------------------------------
export type { Chain };
