// Mock vault data for demo
export const mockVaults = [
    {
        id: '1',
        merchant: 'Dubai Electronics Store',
        description: 'Inventory financing for Q1 2026 expansion',
        targetAmount: 50000,
        totalRaised: 35000,
        interestRate: 12,
        duration: 6,
        numTranches: 3,
        investorCount: 24,
        status: 'fundraising',
        deadline: new Date('2026-03-15').getTime(),
        category: 'Retail',
        riskScore: 'A',
    },
    {
        id: '2',
        merchant: 'Al Barsha Restaurant',
        description: 'Equipment upgrade and kitchen expansion',
        targetAmount: 30000,
        totalRaised: 30000,
        interestRate: 15,
        duration: 4,
        numTranches: 2,
        investorCount: 18,
        status: 'active',
        deadline: new Date('2026-02-20').getTime(),
        category: 'F&B',
        riskScore: 'B+',
    },
    {
        id: '3',
        merchant: 'Marina Fashion Boutique',
        description: 'Summer collection inventory purchase',
        targetAmount: 25000,
        totalRaised: 18500,
        interestRate: 10,
        duration: 3,
        numTranches: 2,
        investorCount: 15,
        status: 'fundraising',
        deadline: new Date('2026-03-01').getTime(),
        category: 'Fashion',
        riskScore: 'A-',
    },
    {
        id: '4',
        merchant: 'Tech Hub Dubai',
        description: 'Office expansion and equipment',
        targetAmount: 75000,
        totalRaised: 52000,
        interestRate: 14,
        duration: 8,
        numTranches: 4,
        investorCount: 32,
        status: 'fundraising',
        deadline: new Date('2026-03-30').getTime(),
        category: 'Technology',
        riskScore: 'A+',
    },
    {
        id: '5',
        merchant: 'JBR Fitness Center',
        description: 'New equipment and facility upgrade',
        targetAmount: 40000,
        totalRaised: 40000,
        interestRate: 11,
        duration: 5,
        numTranches: 3,
        investorCount: 22,
        status: 'repaying',
        deadline: new Date('2026-01-15').getTime(),
        category: 'Health',
        riskScore: 'A',
    },
    {
        id: '6',
        merchant: 'Downtown Cafe Chain',
        description: 'Third location opening - working capital',
        targetAmount: 60000,
        totalRaised: 60000,
        interestRate: 13,
        duration: 6,
        numTranches: 3,
        investorCount: 28,
        status: 'completed',
        deadline: new Date('2025-12-01').getTime(),
        category: 'F&B',
        riskScore: 'A-',
    },
]

export const mockInvestments = [
    {
        vaultId: '2',
        merchant: 'Al Barsha Restaurant',
        amountInvested: 5000,
        debtTokens: 5000,
        claimedReturns: 1250,
        totalReturns: 5750,
        investedAt: new Date('2025-12-15').getTime(),
        status: 'active',
    },
    {
        vaultId: '5',
        merchant: 'JBR Fitness Center',
        amountInvested: 3000,
        debtTokens: 3000,
        claimedReturns: 500,
        totalReturns: 3330,
        investedAt: new Date('2025-11-20').getTime(),
        status: 'repaying',
    },
    {
        vaultId: '6',
        merchant: 'Downtown Cafe Chain',
        amountInvested: 8000,
        debtTokens: 8000,
        claimedReturns: 9040,
        totalReturns: 9040,
        investedAt: new Date('2025-10-01').getTime(),
        status: 'completed',
    },
]

export const mockICMVaults = [
    {
        id: 'icm1',
        business: 'TechStart Dubai',
        description: 'AI-powered customer service platform',
        totalShares: 100000,
        sharesSold: 45000,
        pricePerShare: 10,
        minBuy: 100,
        maxBuy: 10000,
        investorCount: 12,
        status: 'active',
        category: 'Technology',
        totalDividends: 15000,
    },
    {
        id: 'icm2',
        business: 'Green Energy Solutions',
        description: 'Solar panel installation services',
        totalShares: 50000,
        sharesSold: 50000,
        pricePerShare: 20,
        minBuy: 50,
        maxBuy: 5000,
        investorCount: 24,
        status: 'closed',
        category: 'Energy',
        totalDividends: 45000,
    },
]

export const mockLiquidityPools = [
    {
        id: 'alpha',
        name: 'TigerPay Alpha Vault',
        type: 'treasury' as const,
        totalCapital: 2500000,
        deployed: 1800000,
        available: 700000,
        apy: 8.5,
        vaultAllocations: 12,
        partnerCount: 1,
        status: 'active' as const,
    },
    {
        id: 'pool1',
        name: 'Gulf Capital Partners',
        type: 'co-owned' as const,
        totalCapital: 500000,
        deployed: 320000,
        available: 180000,
        apy: 9.2,
        vaultAllocations: 6,
        partnerCount: 3,
        status: 'active' as const,
    },
    {
        id: 'pool2',
        name: 'MENA Growth Fund',
        type: 'co-owned' as const,
        totalCapital: 750000,
        deployed: 450000,
        available: 300000,
        apy: 8.8,
        vaultAllocations: 8,
        partnerCount: 5,
        status: 'active' as const,
    },
    {
        id: 'pool3',
        name: 'Digital Commerce Pool',
        type: 'co-owned' as const,
        totalCapital: 300000,
        deployed: 280000,
        available: 20000,
        apy: 10.1,
        vaultAllocations: 4,
        partnerCount: 2,
        status: 'near-cap' as const,
    },
]

export const mockPoolAllocations = [
    { id: 'a1', pool: 'TigerPay Alpha Vault', vault: 'Dubai Electronics Store', amount: 150000, date: '2026-01-10', status: 'active' as const },
    { id: 'a2', pool: 'Gulf Capital Partners', vault: 'Al Barsha Restaurant', amount: 45000, date: '2026-01-15', status: 'active' as const },
    { id: 'a3', pool: 'MENA Growth Fund', vault: 'Tech Hub Dubai', amount: 120000, date: '2026-01-20', status: 'active' as const },
    { id: 'a4', pool: 'TigerPay Alpha Vault', vault: 'JBR Fitness Center', amount: 80000, date: '2025-12-05', status: 'repaying' as const },
    { id: 'a5', pool: 'Digital Commerce Pool', vault: 'Marina Fashion Boutique', amount: 30000, date: '2026-02-01', status: 'active' as const },
    { id: 'a6', pool: 'TigerPay Alpha Vault', vault: 'Downtown Cafe Chain', amount: 200000, date: '2025-10-01', status: 'completed' as const },
]
